[update] fix lib compile warning, due to non-std function netinet/in.h inet6_rth_*
wrapsock.c: In function ‘Inet6_rth_space’:
wrapsock.c:81:2: warning: implicit declaration of function
‘inet6_rth_space’ [-Wimplicit-function-declaration]
wrapsock.c: In function ‘Inet6_rth_init’:
wrapsock.c:93:2: warning: implicit declaration of function
‘inet6_rth_init’ [-Wimplicit-function-declaration]
wrapsock.c:93:6: warning: assignment makes pointer from integer without
a cast [enabled by default]
wrapsock.c: In function ‘Inet6_rth_add’:
wrapsock.c:103:2: warning: implicit declaration of function
‘inet6_rth_add’ [-Wimplicit-function-declaration]
wrapsock.c: In function ‘Inet6_rth_reverse’:
wrapsock.c:110:2: warning: implicit declaration of function
‘inet6_rth_reverse’ [-Wimplicit-function-declaration]
wrapsock.c: In function ‘Inet6_rth_segments’:
wrapsock.c:119:2: warning: implicit declaration of function
‘inet6_rth_segments’ [-Wimplicit-function-declaration]
wrapsock.c: In function ‘Inet6_rth_getaddr’:
wrapsock.c:131:2: warning: implicit declaration of function
‘inet6_rth_getaddr’ [-Wimplicit-function-declaration]
wrapsock.c:131:6: warning: assignment makes pointer from integer without
a cast [enabled by default]